// Generated by scripts/fetch-samples.mjs. Do not edit by hand.

import s1 from './nylon/E2.mp3'
import s2 from './nylon/A2.mp3'
import s3 from './nylon/D3.mp3'
import s4 from './nylon/G3.mp3'
import s5 from './nylon/B3.mp3'
import s6 from './nylon/E4.mp3'
import s7 from './nylon/E3.mp3'
import s8 from './nylon/A3.mp3'
import s9 from './nylon/D4.mp3'
import s10 from './nylon/G4.mp3'
import s11 from './nylon/B4.mp3'
import s12 from './nylon/E5.mp3'
import s13 from './steel/E2.mp3'
import s14 from './steel/A2.mp3'
import s15 from './steel/D3.mp3'
import s16 from './steel/G3.mp3'
import s17 from './steel/B3.mp3'
import s18 from './steel/E4.mp3'
import s19 from './steel/E3.mp3'
import s20 from './steel/A3.mp3'
import s21 from './steel/D4.mp3'
import s22 from './steel/G4.mp3'
import s23 from './steel/B4.mp3'
import s24 from './steel/E5.mp3'
import s25 from './electric/E2.mp3'
import s26 from './electric/A2.mp3'
import s27 from './electric/D3.mp3'
import s28 from './electric/G3.mp3'
import s29 from './electric/B3.mp3'
import s30 from './electric/E4.mp3'
import s31 from './electric/E3.mp3'
import s32 from './electric/A3.mp3'
import s33 from './electric/D4.mp3'
import s34 from './electric/G4.mp3'
import s35 from './electric/B4.mp3'
import s36 from './electric/E5.mp3'
import s37 from './jazz/E2.mp3'
import s38 from './jazz/A2.mp3'
import s39 from './jazz/D3.mp3'
import s40 from './jazz/G3.mp3'
import s41 from './jazz/B3.mp3'
import s42 from './jazz/E4.mp3'
import s43 from './jazz/E3.mp3'
import s44 from './jazz/A3.mp3'
import s45 from './jazz/D4.mp3'
import s46 from './jazz/G4.mp3'
import s47 from './jazz/B4.mp3'
import s48 from './jazz/E5.mp3'
import s49 from './fret-noise/E3.mp3'
import s50 from './fret-noise/B3.mp3'
import s51 from './fret-noise/E4.mp3'

export const SAMPLE_FILES: Record<string, Record<string, string>> = {
  "nylon": {
    "E2": s1,
    "A2": s2,
    "D3": s3,
    "G3": s4,
    "B3": s5,
    "E4": s6,
    "E3": s7,
    "A3": s8,
    "D4": s9,
    "G4": s10,
    "B4": s11,
    "E5": s12,
  },
  "steel": {
    "E2": s13,
    "A2": s14,
    "D3": s15,
    "G3": s16,
    "B3": s17,
    "E4": s18,
    "E3": s19,
    "A3": s20,
    "D4": s21,
    "G4": s22,
    "B4": s23,
    "E5": s24,
  },
  "electric": {
    "E2": s25,
    "A2": s26,
    "D3": s27,
    "G3": s28,
    "B3": s29,
    "E4": s30,
    "E3": s31,
    "A3": s32,
    "D4": s33,
    "G4": s34,
    "B4": s35,
    "E5": s36,
  },
  "jazz": {
    "E2": s37,
    "A2": s38,
    "D3": s39,
    "G3": s40,
    "B3": s41,
    "E4": s42,
    "E3": s43,
    "A3": s44,
    "D4": s45,
    "G4": s46,
    "B4": s47,
    "E5": s48,
  },
  "fret-noise": {
    "E3": s49,
    "B3": s50,
    "E4": s51,
  },
}
